Feature/account tab
MarianMocanu/washworld-mobile-app pull request #2
Opened 2024-05-13 12:34 UTC by ThordurTh

Created a stack navigator in the "AccountScreen" file. Created all the screens and styled the main "AccountSettingsScreen" according to the Figma design and amde all other screens accessible.

2024-05-13 12:47 UTC, MarianMocanu requested changes

2024-05-13 12:47 UTC, MarianMocanu commented on src/features/account/screens/AccountSettingsScreen.tsx
improve and reuse the custom Button component and use it for the SettingsButton

2024-05-13 12:47 UTC, MarianMocanu commented on src/features/account/screens/AddAnotherCarScreen.tsx
reuse the Button custom component here as well

2024-05-15 17:54 UTC, ThordurTh commented on src/features/account/screens/AddAnotherCarScreen.tsx
I suppose that shouldn't be necessary since this button is just temporary in order to be able to go back and can be found on all of the screens within the account settings screen.

2024-05-16 09:52 UTC, MarianMocanu approved these changes

2024-05-16 09:55 UTC, merged